name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.1

   # Local storage / prefs
  shared_preferences: ^2.3.2

  # Networking & platform
  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0

  # QR code UI
  qr_flutter: ^4.1.0

  # Notifications & time utilities
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.3
  intl: ^0.19.0

  flex_color_scheme: ^8.0.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.0
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
